import { ThemeProvider } from "./exports";
import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Instadoc",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <Header />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
